### ISSUE TITLE
INFORMATION_SCHEMA.PARTITIONS requests are limited to 1000 tables

### ISSUE THREAD

**Issue by Kayrnt** [bqbooster/dbt-bigquery-monitoring#46]
See https://cloud.google.com/bigquery/docs/information-schema-partitions
It leads to failing executions of models on setup with more than 1000 tables

**Comment by Kayrnt** [comment]
As there's no immediate workaround (maybe through a dedicated materialization like for project one).
In the meantime, if you run into the issue, you can disable the related model by adding in your configuration (`dbt_project.yml`) :
```yml
...
models:
  dbt_bigquery_monitoring:
    monitoring:
      storage:
        datamart:
          table:
            partitions_monitoring:
              +enabled: false
        intermediate:
          stg_partitions_monitoring:
            +enabled: false
```

**Comment by aw-stevens** [comment]
@Kayrnt I think I've run into this limitation, by way of the following error message: "INFORMATION_SCHEMA.PARTITIONS query attempted to read too many tables. Please add more restrictive filters."

We arrived at a similar workaround as described above (hadn't seen this issue), and can confirm it works:

```
dbt_bigquery_monitoring:
  information_schema:
    tables:
      information_schema_partitions:
        +enabled: false
  monitoring:
    storage:
      intermediate:
        stg_partitions_monitoring:
          +enabled: false
      datamart:
        table:
          partitions_monitoring:
            +enabled: false
```

That said, I was able to identify a somewhat more-elegant fix/workaround, that might be worth including in the official package.

## Proposed Fix
Add an `input_datasets` var to `get_dataset_list()`. When set, the macro returns the explicit list instead of querying SCHEMATA. This scopes the PARTITIONS fan-out to a manageable subset and is a no-op for users who don't set the var.

```
{% macro get_dataset_list() %}
  {% if execute %}
    {% set input_datasets = var('input_datasets', []) %}

    {% if input_datasets | length > 0 %}
      {% set dataset_list = [] %}
      {% for dataset in input_datasets %}
        {% set parts = dataset.split('.') %}
        {% do dataset_list.append('`' ~ parts[0] ~ '`.`' ~ parts[1] ~ '`') %}
      {% endfor %}
      {{ return(dataset_list) }}

    {% else %}
      {# existing SCHEMATA query behavior ... #}
    {% endif %}
  {% else %}
    {{ return([]) }}
  {% endif %}
{% endmacro %}
```

Users would configure it in `dbt_project.yml`:
```
vars:
  input_datasets:
    - 'my-gcp-project.my_dbt_prod_target'
```

We've prototyped this locally and it resolves the error — `partitions_monitoring` runs successfully and returns the expected data.

## Notes
- This might not help every user, e.g. if your dbt project itself has more than 1k models. But for folks like use, whose BigQuery project contains a ton of datasets not used nor created by dbt, then focusing the partition monitoring on our dbt dev/staging/prod datasets here is certainly better than the alternative
- This same `input_datasets` var would also scope the other `get_dataset_list()` consumers (`information_schema_key_column_usage`, `information_schema_constraint_column_usage`, `information_schema_search_indexes*`) to the specified datasets. In our case that'd have be fine — but it's worth calling out in the docs.
- A root-project macro override with the same name does not work here: dbt resolves macro calls within a package by searching the package's own macros first, so the override never reaches the package's model. The fix must be in the package itself (or via a supported dispatch mechanism).
